name: CICD
  
on: 
    workflow_dispatch:
jobs:
    code:
      runs-on: ubuntu-latest
      steps:
        - name: clone the code
          run: echo "cloning the code"
        
    build:
      needs: [code]
      runs-on: ubuntu-latest
      steps:
        - name: Build using Docker
          run: echo "Building using Docker"
                 
    test:
      needs: [build]
      runs-on: ubuntu-latest
      steps:
        - name: Running test cases
          run: echo "Testing the App"
          
    deploy:
      needs: [test]
      runs-on: ubuntu-latest
      steps:
        - name: Deploying on the machine
          run: echo "deploying the code"
  
